version: "3.9"

services:
  front-end:
    restart: "unless-stopped"
    container_name: "user-portal"
    build:
      context: 'user_portal/'
      dockerfile: 'docker/Dockerfile'
    command: 'python src/user_portal.py'
    volumes:
      - "./user_portal/src:/app/work/src"
    ports:
      - '8050:8050'                     # Do we need to change the port?
