version: "3.9"

services:
  front-end:
    depends_on:
      - user-api
    restart: "unless-stopped"
    container_name: "user-portal"
    build:
      context: 'user_portal/'
      dockerfile: 'docker/Dockerfile'
    command: 'python src/router.py'
    volumes:
      - "./user_portal/src:/app/work/src"
    ports:
      - '8050:8050'
    environment:
      - USER_API=user-api

  user-api:
      restart: "unless-stopped"
      container_name: "user-api"
      build:
        context: "user_api/"
        dockerfile: "docker/Dockerfile"
      volumes:
        - ./user_api/src:/app/api/src
      expose:
        - "5000"
      ports:
        - "5000:5000"